### ISSUE TITLE
Error: missing 1 required positional argument: 'fallbackTitle'

### ISSUE THREAD

**Issue by ProactiveServices** [GeoffreyCoulaud/samsung-memos-to-json#1]
Using script as at commit 7983dda I received the following error: 
```
Reading memos dir
Converting memos to notes
Memo "Memo_20220103_170001_326"
* Extracting
* Parsing
* Creating note
Traceback (most recent call last):
File "samsung-memo-to-notes.py", line 158, in <module>
main()
File "samsung-memo-to-notes.py", line 149, in main
convert(
File "samsung-memo-to-notes.py", line 117, in convert
note = memoXmlToNote(tree)
TypeError: memoXmlToNote() missing 1 required positional argument: 'fallbackTitle'
```

I have little python experience but after commenting out the "fallbackTitle" argument parsing lines, removing the "fallbackTitle" function variables and inserting `fallbackTitle = "No title"` in `convert()` and `memoXmlToNote()` functions (effectively hard-coding fallbackTitle), the script completed.

**Comment by GeoffreyCoulaud** [comment]
My bad, I never realised that fallbackTitle is never passed when calling `memoXmlToNote`.  
Latest commit should have fixed it.

**Comment by ProactiveServices** [comment]
I've erased the client data I was working with but am confident you've fixed it. Thank you!
